# Lab3 实验报告

>  姓名： 谭栋泽
>
> 学号：23336011



[TOC]



## 实验结果

![image-20250711152041960](C:\Users\ltdjcoder\AppData\Roaming\Typora\typora-user-images\image-20250711152041960.png) 

正确的产生时钟中断， 并且观测到系统进程不断被调度运行， 而且调度后正常的继续执行，结果没有问题。

-------------

使用test命令 正确产生新的测试系统线程，并且轮流调度

![image-20250711182748542](C:\Users\ltdjcoder\AppData\Roaming\Typora\typora-user-images\image-20250711182748542.png) 

> 这副图片说明： 加入测试线程后，经历了 系统线程 -> 测试线程 -> 系统线程的调度
>
> 具体分别表现为： 输入有响应 ， 输入无相应 ， 延迟响应了之前的输入且输入有响应。

------------



## 实验过程

首先按照教程的推荐，先将实验文档通读一遍大概明白在做什么。

接下来让我们阅读开头给出的那个代码结构示意图，看看哪些可以用到，可能在什么时候用到。

![img](https://ysos.gzti.me/labs/assets/proc.png)

### clone页表

我们首先遇到一个报错， `clone_page_table`好像没有正确实现，我们要尝试实现这个clone，文档中说“只要复制根节点就行”这应该是指我们只需要浅拷贝？

我们先看看具体的页表实现再作决定吧， 页表中实现了一个`clone_level_4`方法，哦这好像是说只复制第四级也就是root，我一开始没有懂什么是clone_level_4，现在发现确实是这个意思。（我都考虑获取copy接口来浅拷贝了，但看着应该是要复制根节点的数据因为不是只读，好像没那么浅

```rust
pub fn clone_page_table(&self) -> PageTableContext {
    // FIX-ME
    self.proc_vm.as_ref().unwrap().page_table.clone_level_4()
}
```



### 系统进程

额好像没有set_status的接口， 会令人迷惑究竟是没有还是在某个地方

```rust
// FIX-ME: set init process as Running
    init.write().set_status(ProgramStatus::Running);
```

这里有点诡异？但先这样，我是想通过manager设置的，等后面完善再议

```rust
// FIX-ME: set processor's current pid to init's pid
    processor::set_pid(init.pid());
```



### 时钟栈

```rust
pub unsafe fn register_idt(idt: &mut InterruptDescriptorTable) {
    idt[Interrupts::IrqBase as u8 + Irq::Timer as u8]
        .set_handler_fn(clock_interrupt_handler)
        .set_stack_index(CLOCK_INTERRUPT_IST_INDEX); 
}
```

代码仿写



### 时钟中断

我现在疑似创建不了`ProcessContext`， 来点构造函数

问题是我好像不知道这里怎么读取寄存器的值？reg里面实际上没有相关接口吗？这应该需要汇编

然后我不确定用as_handler之后还能不能读到值，让我思考这些问题。

哦，那我想到更为合适的处理方法了， 我应该尝试去修改这个`as_handler`的定义，使得我不仅仅能够得到InterruptStackFrame， 还有reg_value。这样确实很好， 但是这好像是某种特定的函数形式，我可能不能修改它。

-----

是是是， 很有这种问题， 受限于我有限的rust和汇编水平，我选择暂时的，先采取一种退而求其次的方法，他应该是线程不安全的。

```rust
/// 获取当前保存的寄存器值
pub fn get_current_registers() -> RegistersValue {
    unsafe { CURRENT_REGISTERS }
}
```

```rust
out("r15") unsafe { CURRENT_REGISTERS.r15 },
out("r14") unsafe { CURRENT_REGISTERS.r14 },
out("r13") unsafe { CURRENT_REGISTERS.r13 },
out("r12") unsafe { CURRENT_REGISTERS.r12 },
out("r11") unsafe { CURRENT_REGISTERS.r11 },
out("r10") unsafe { CURRENT_REGISTERS.r10 },
out("r9") unsafe { CURRENT_REGISTERS.r9 },
out("r8") unsafe { CURRENT_REGISTERS.r8 },
out("rdi") unsafe { CURRENT_REGISTERS.rdi },
out("rsi") unsafe { CURRENT_REGISTERS.rsi },
out("rdx") unsafe { CURRENT_REGISTERS.rdx },
out("rcx") unsafe { CURRENT_REGISTERS.rcx },
out("rbx") unsafe { CURRENT_REGISTERS.rbx },
out("rax") unsafe { CURRENT_REGISTERS.rax },
out("rbp") unsafe { CURRENT_REGISTERS.rbp },
```

也算是解决问题？

现在我们可有构造函数

```rust
pub fn new(stack_frame: InterruptStackFrameValue, reg_value: RegistersValue) -> Self{
    Self{
        value: ProcessContextValue {
            regs: reg_value,
            stack_frame,
        }
    }
}   
```

嘶不对

```rust
pub extern "C" fn clock_interrupt(mut context: ProcessContext) {
    x86_64::instructions::interrupts::without_interrupts(|| {
        proc::switch(&mut context);
        super::ack();
    });
}
```

诶，这里为啥直接能拿到`ProcessContext`？额我好像大费周章没起作用。哎呦。不过我确实没看出来这玩意哪里产生的。



### 进程调度

实验三的引导非常完善且友好，让我总算有点摸得着头绪可以按自己的想法略作修改了。

其实我觉得这个restore应该是manager的职责吧（这里暂且按照原有做了）

```rust
proc.as_ref().write().restore();
```

然后设置进程的运行状态， 进程可以暴露接口，但谁来负责调用这个切换？我觉得是明显是管理器，调度器负责调度，自然负责各个进程的状态保存，加载，运行状态的变更（甚至tick的加一)。在restore里面偷偷变就很奇怪了， 这个restore的自责不太明确。可能不太符合我的编程思维，可以修改：

```rust
// FIXME: switch to the next process
    //      - save current process's context
    //      - handle ready queue update
    //      - restore next process's context
    // 我直接大搬迁
    // 换下一个：先存这个，在找下个，加载下个，全都考虑队列
pub fn switch_next(&self, context: &mut ProcessContext) -> ProcessId {

    self.current().write().set_status(ProgramStatus::Ready);
    self.save_current(context);
    self.ready_queue.lock().push_back(processor::get_pid());

    // FIXM-E: fetch the next process from ready queue
    let mut ready_queue = self.ready_queue.lock();
    let mut next_pid_result = ready_queue.pop_front();
    let mut next_pid = ProcessId(0);


    // FIX-ME: check if the next process is ready,
    //        continue to fetch if not ready
    while let Some(pid) = next_pid_result {
        if let Some(proc) = self.get_proc(&pid) {
            if proc.read().status() == ProgramStatus::Ready {
                next_pid = pid;
                break;
            }else{
                self.ready_queue.lock().push_back(pid);
            }
        }
        // If not ready, continue to fetch the next one
        next_pid_result = ready_queue.pop_front();
    }

    // FIX-ME: restore next process's context
    if let Some(proc) = self.get_proc(&next_pid) {
        proc.as_ref().write().restore(); 
        proc.as_ref().write().set_status(ProgramStatus::Running);
    } else {
        warn!("No process found for pid: {}", next_pid);
        return ProcessId(0); 
    }

    // FIXME: update processor's current pid
    processor::set_pid(next_pid);

    // FIXME: return next process's pid
    next_pid
}
```

我干脆把prco::switch那个函数删了，我觉得都是manager的责任。

这个函数太长了， 应该具体细分功能会更好。

现在问题是这个restore我可能不太懂什么情况。感觉还要汇编。

> 1. 使用 `pause`、`resume` 等函数来构造更具有可读性的代码。

你是对的，我这就改。

```rust
// proc.as_ref().write().set_status(ProgramStatus::Running);
proc.as_ref().write().resume();
// self.current().write().set_status(ProgramStatus::Ready);
self.current().write().pause();
```

> 你可以通过 `drop` 函数在合适的时候主动释放取得的锁。

诶，我好像不用，因为我全部是这样的

```rust
self.ready_queue.lock().push_back(pid);
```

没有临时变量，锁会直接过期释放，好像有个书说法是少用临时变量，可以让重构的时候提取更加简单，现在看好处还挺多，我深以为然。

### 缺页异常

我又遇到了Double Fault ， 经过阅读代码，我发现应该是没有给处理函数的栈初始化导致的。

正确解决。

```rust
[INFO ] ysos_kernel::interrupt::clock: Clock interrupt happen.
[INFO ] ysos_kernel::proc::manager: Handling page fault at VirtAddr(
    0x3ffdffff7fb8,
) with error code: PageFaultErrorCode(CAUSED_BY_WRITE)
Huge stack testing...
0x000 == 0x000
0x100 == 0x100
0x200 == 0x200
0x300 == 0x300
0x400 == 0x400
0x500 == 0x500
0x600 == 0x600
0x700 == 0x700
0x800 == 0x800
0x900 == 0x900
0xa00 == 0xa00
0xb00 == 0xb00
0xc00 == 0xc00
0xd00 == 0xd00
0xe00 == 0xe00
0xf00 == 0xf00
[INFO ] ysos_kernel::interrupt::clock: Clock interrupt happen.
[INFO ] ysos_kernel::interrupt::clock: Clock interrupt happen.
[ERROR] ysos_kernel::utils::macros: KERNEL PANIC!
[ERROR] ysos_kernel::utils::macros: Panic occurred in file 'pkg/kernel/src/proc/process.rs' at line 140
[ERROR] ysos_kernel::utils::macros: Panic message: called `Option::unwrap()` on a `None` value
qemu-system-x86_64: QEMU: Terminated via GDBstub
```

又出现了这个问题。 我想了一会，应该是正确执行了， 但是没有退出，导致vm被释放。

那就是合理的，这一部分正确完成。

--------------

### 退出进程















